[package]
name = "rust_os"
version = "0.1.0"
edition = "2021"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package.metadata.bootimage]
build-command = ["build"]

[dependencies]
bootloader = "0.9.23"
